version: '3.2'

networks:
  sonarnet:
    driver: overlay
    attachable: true
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.10.33,nolock,soft,rw
      device: ":/media/1800g/swarm-volume/sonarqube/postgresql"
  postgresql_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.10.33,nolock,soft,rw
      device: ":/media/1800g/swarm-volume/sonarqube/postgresql/data"
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9001:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    deploy:
      mode: replicated
      replicas: 1
  db:
    image: postgres
    container_name: sonarqube_db
    ports:
      - "5433:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
